export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_PRODUCT = "SET_PRODUCT";
export const SET_WISHLIST = "SET_WISHLIST";
export const SET_RELATED_PRODUCTS = "SET_RELATED_PRODUCTS";
export const SET_USER_CREDENTIALS = "SET_USER_CREDENTIALS";